# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  SpaceShip_Game_config = release

else ifeq ($(config),debug)
  SpaceShip_Game_config = debug

else ifeq ($(config),dev)
  SpaceShip_Game_config = dev

else ifeq ($(config),devdebug)
  SpaceShip_Game_config = devdebug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := SpaceShip_Game

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

SpaceShip_Game:
ifneq (,$(SpaceShip_Game_config))
	@echo "==== Building SpaceShip_Game ($(SpaceShip_Game_config)) ===="
	@${MAKE} --no-print-directory -C SpaceShip_Game -f Makefile config=$(SpaceShip_Game_config)
endif

clean:
	@${MAKE} --no-print-directory -C SpaceShip_Game -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo "  dev"
	@echo "  devdebug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SpaceShip_Game"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"